import type { Metadata } from "next"
import Image from "next/image"
import Link from "next/link"
import { Header } from "@/components/layout/header"
import { Footer } from "@/components/layout/footer"
import MacroCalculator from "@/components/calculators/macro-calculator"
import { CalculatorSchema, FAQSchema } from "@/components/seo/structured-data"
import { FAQSection } from "@/components/seo/faq-section"
import { Card, CardHeader, CardContent, CardTitle, CardDescription } from "@/components/ui/card"
import { 
  Beef, 
  Wheat, 
  Leaf, 
  Dumbbell, 
  Calculator as CalculatorIcon, 
  AlertCircle, 
  TrendingUp, 
  Apple, 
  Info,
  Globe,
  CheckCircle2,
  Target,
  TrendingDown
} from "lucide-react"

export const metadata: Metadata = {
  title: "Macro Calculator (Free & Accurate) – Calculate Macros for Weight Loss & Muscle Gain",
  description:
    "Calculate your ideal daily macros for weight loss, muscle gain, or maintenance. Trusted by professionals at calqulate.net for science-backed nutrition planning.",
  keywords:
    "macro calculator, calculate macros, macro calculator for weight loss, macros for muscle gain, protein calculator, calqulate.net, nutrition tool",
}

const faqs = [
  {
    question: "How do I calculate macros manually?",
    answer:
      "To calculate macros, you first find your TDEE (total calories). Then: 1. Set Protein (usually 0.8-1g per lb of body weight). 2. Set Fats (usually 20-30% of total calories). 3. Fill the remaining calories with Carbohydrates. Our calculator at calqulate.net automates this science-backed formula for you.",
  },
  {
    question: "Is this macro calculator suitable for vegetarians?",
    answer:
      "Yes. While the targets remain the same, vegetarians should focus on high-protein plant sources like lentils, tofu, and tempeh to hit the protein targets generated by the calculator.",
  },
  {
    question: "Why are my macros different from another calculator?",
    answer:
      "Different calculators use different base formulas (Mifflin-St Jeor vs. Harris-Benedict) or different activity multipliers. Calqulate.net uses the most updated research to ensure your targets are sustainable and realistic.",
  },
  {
    question: "Do I have to track every single gram to see results?",
    answer:
      "No. Consistency beats perfection. Aiming to be within +/- 10 grams of your targets is usually enough for 90% of people to see significant body composition changes.",
  },
  {
    question: "Can I use this for a Keto diet?",
    answer:
      "This calculator is designed for balanced nutrition. For Keto, you would manually need to set fats to 70%+, protein to 20-25%, and carbs to 5-10%. However, our 'Protein-First' approach works better for long-term muscle preservation.",
  },
]

export default function MacroCalculatorPage() {
  return (
    <div className="min-h-screen flex flex-col bg-white">
      <CalculatorSchema
        name="Macro Calculator"
        description="Calculate your daily protein, carbs, and fats based on your fitness goals."
        url="https://calqulate.net/fitness/macro-calculator"
      />
      <FAQSchema faqs={faqs} />

      <Header />

      <main className="flex-1">
        <div className="container mx-auto px-4 py-8">
          <div className="max-w-4xl mx-auto">
            {/* Hero */}
            <div className="text-center mb-8">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 text-blue-700 text-sm font-medium mb-4">
                <Target className="w-4 h-4" /> Trusted by beginners and professionals across USA, UK & India
              </div>
              <h1 className="text-3xl md:text-5xl font-extrabold text-balance mb-6 tracking-tight text-gray-900">
                Macro Calculator (Free & Accurate) – Calculate Macros for Weight Loss, Muscle Gain & Maintenance
              </h1>
              <p className="text-xl text-muted-foreground text-pretty max-w-2xl mx-auto">
                If you&apos;re searching for a macro calculator that actually explains what to do with the numbers, you&apos;re in the right place.
              </p>
            </div>

            {/* Calculator Component */}
            <MacroCalculator />

            <div className="prose prose-gray max-w-none mt-16 space-y-16">

              {/* Simple Explanation */}
              <section>
                <h2 className="text-2xl font-bold mb-6">What Is a Macro Calculator?</h2>
                <p className="text-gray-700">
                  A macros calculator tells you how many grams of <strong>protein, carbohydrates, and fats</strong> you should eat each day based on your age, gender, height, weight, activity level, and specific goal.
                </p>
                <div className="grid md:grid-cols-2 gap-4 not-prose mt-8">
                  <Card className="border-none bg-blue-50 shadow-sm">
                    <CardHeader>
                      <CardTitle className="text-lg flex items-center gap-2">
                        <Info className="text-blue-600" /> Key Question 1
                      </CardTitle>
                    </CardHeader>
                    <CardContent>How much should I eat total (Calories)?</CardContent>
                  </Card>
                  <Card className="border-none bg-green-50 shadow-sm">
                    <CardHeader>
                      <CardTitle className="text-lg flex items-center gap-2">
                        <Info className="text-green-600" /> Key Question 2
                      </CardTitle>
                    </CardHeader>
                    <CardContent>What should those calories be made of?</CardContent>
                  </Card>
                </div>
              </section>

              {/* Why Most Calculators Fail */}
              <section>
                <h2 className="text-2xl font-bold mb-6">Why Most Macro Calculators Fail (And Why Results Stall)</h2>
                <p className="text-gray-700 mb-4">
                  Most popular calculators give numbers without context, ignore food culture (especially UK & India), assume perfect tracking, and never explain how to adjust macros.
                </p>
                <p className="text-gray-700 mb-6">
                  That's why people say "macros didn't work for me." Macros didn't fail — the guidance did.
                </p>
                <div className="grid md:grid-cols-2 gap-4 not-prose">
                  {[
                    "Give numbers without context",
                    "Ignore regional food habits",
                    "Assume perfect tracking",
                    "Never explain adjustments"
                  ].map((item, i) => (
                    <div key={i} className="flex items-center gap-3 p-4 border rounded-xl bg-red-50 border-red-200">
                      <AlertCircle className="w-5 h-5 text-red-500 shrink-0" />
                      <span className="text-gray-700">{item}</span>
                    </div>
                  ))}
                </div>
              </section>

              {/* Differences */}
              <section>
                <h2 className="text-2xl font-bold mb-4">How calqulate.net is Different</h2>
                <p className="mb-6">Most calculators give numbers without context. We focus on a framework that actually works:</p>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 not-prose">
                  {[
                    "Protein-first approach (non-negotiable)",
                    "Moderate calorie deficit (no crash dieting)",
                    "Adaptive macros (recalculate as you change)",
                    "Regional diet habits (USA, UK, AU, IN)",
                    "Works for gym, home workouts & busy lifestyles"
                  ].map((item, i) => (
                    <div key={i} className="flex items-center gap-3 p-4 border rounded-xl bg-white shadow-sm">
                      <CheckCircle2 className="w-5 h-5 text-green-500 shrink-0" />
                      <span className="font-medium text-gray-700">{item}</span>
                    </div>
                  ))}
                </div>
              </section>

              {/* Weight Loss vs Muscle Gain */}
              <section className="grid md:grid-cols-2 gap-12">
                <div>
                  <h3 className="text-xl font-bold mb-4 flex items-center gap-2 text-red-600">
                    <TrendingDown className="w-5 h-5" /> For Weight Loss
                  </h3>
                  <ul className="space-y-4 text-sm text-gray-600 list-none p-0">
                    <li className="bg-slate-50 p-3 rounded-lg"><strong>Smart Deficit:</strong> 10–20% below maintenance. No crash diets.</li>
                    <li className="bg-slate-50 p-3 rounded-lg"><strong>Lock in Protein:</strong> 1.6–2.2 g per kg to preserve muscle.</li>
                    <li className="bg-slate-50 p-3 rounded-lg"><strong>Adjust Carbs:</strong> Reduce carbs gradually to fuel workouts.</li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-xl font-bold mb-4 flex items-center gap-2 text-blue-600">
                    <Dumbbell className="w-5 h-5" /> For Muscle Gain
                  </h3>
                  <ul className="space-y-4 text-sm text-gray-600 list-none p-0">
                    <li className="bg-slate-50 p-3 rounded-lg"><strong>Lean Bulk:</strong> Small calorie surplus (5–10%).</li>
                    <li className="bg-slate-50 p-3 rounded-lg"><strong>Fuel Training:</strong> Higher carbs for performance.</li>
                    <li className="bg-slate-50 p-3 rounded-lg"><strong>Minimize Fat:</strong> Avoid unnecessary &quot;dirty bulking&quot;.</li>
                  </ul>
                </div>
              </section>

              {/* Macro Breakdown Table */}
              <section>
                <h2 className="text-2xl font-bold mb-6">Protein, Carbs & Fat Explained</h2>
                <Card className="not-prose overflow-hidden border-none shadow-xl">
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm border-collapse">
                      <thead className="bg-gray-900 text-white">
                        <tr>
                          <th className="px-6 py-4 text-left">Macro</th>
                          <th className="px-6 py-4 text-left">The Purpose</th>
                          <th className="px-6 py-4 text-left">Top Sources</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-100">
                        <tr>
                          <td className="px-6 py-4 font-bold flex items-center gap-2"><Beef className="w-4 h-4 text-red-500" /> Protein</td>
                          <td className="px-6 py-4 text-gray-600">Builds & preserves muscle, improves metabolism.</td>
                          <td className="px-6 py-4 text-gray-600">Chicken, Tofu, Eggs, Whey, Lentils.</td>
                        </tr>
                        <tr>
                          <td className="px-6 py-4 font-bold flex items-center gap-2"><Wheat className="w-4 h-4 text-yellow-600" /> Carbs</td>
                          <td className="px-6 py-4 text-gray-600">Performance fuel, supports training & recovery.</td>
                          <td className="px-6 py-4 text-gray-600">Rice, Oats, Potatoes, Fruits, Roti.</td>
                        </tr>
                        <tr>
                          <td className="px-6 py-4 font-bold flex items-center gap-2"><Leaf className="w-4 h-4 text-green-600" /> Fats</td>
                          <td className="px-6 py-4 text-gray-600">Essential for hormonal health & vitamin absorption.</td>
                          <td className="px-6 py-4 text-gray-600">Nuts, Olive Oil, Avocado, Ghee.</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </Card>
              </section>

              {/* Regional Insights */}
              <section>
                <h2 className="text-2xl font-bold mb-6 flex items-center gap-2">
                  <Globe className="w-6 h-6 text-blue-500" /> Macro Calculator Regional Insights
                </h2>
                <div className="grid md:grid-cols-4 gap-4 not-prose">
                  {[
                    { loc: "USA", desc: "Focus on reducing processed fats and increasing lean protein." },
                    { loc: "UK", desc: "Awareness of hidden carbs in snacks and pub-style meals." },
                    { loc: "Australia", desc: "Supporting high-activity outdoor lifestyles with carbs." },
                    { loc: "India", desc: "Protein planning is critical for vegetarian-heavy diets." }
                  ].map((item) => (
                    <div key={item.loc} className="p-5 rounded-2xl border bg-white hover:border-blue-200 transition-colors">
                      <h4 className="font-bold text-gray-900 mb-2 border-b pb-1">{item.loc}</h4>
                      <p className="text-xs text-gray-600 leading-relaxed">{item.desc}</p>
                    </div>
                  ))}
                </div>
              </section>

              {/* James Smith Comparison */}
              <section className="bg-gray-50 p-8 rounded-3xl">
                <h2 className="text-2xl font-bold mb-4 mt-0">James Smith Macro Calculator – Honest Comparison</h2>
                <p className="text-gray-700">The James Smith macro calculator is popular for its simplicity. While it does well at giving straightforward targets and emphasizing protein, calqulate.net provides more customization for long-term adjustment strategies. We believe a calculator should grow with you, not just give you a static number.</p>
              </section>

              {/* How to Use Macros */}
              <section>
                <h2 className="text-2xl font-bold mb-4">How to Use Macros in Daily Life</h2>
                <p className="mb-6 font-medium text-blue-700 italic">Stop chasing perfection. Consistency beats accuracy.</p>
                <div className="grid md:grid-cols-2 gap-8 items-center">
                   <div className="not-prose space-y-4">
                      {[
                        "Hit your protein goal daily.",
                        "Stay within ±10% of total calories.",
                        "Adjust carbs around your workout windows.",
                        "Track weekly trends, not daily scale weight."
                      ].map((tip, i) => (
                        <div key={i} className="flex gap-3 items-start">
                          <div className="h-6 w-6 rounded-full bg-blue-600 text-white flex items-center justify-center text-xs shrink-0">{i+1}</div>
                          <p className="text-gray-700 text-sm">{tip}</p>
                        </div>
                      ))}
                   </div>
                   <Image 
                      src="/api/placeholder/400/250" 
                      alt="Person tracking food on mobile" 
                      width={400} 
                      height={250} 
                      className="rounded-2xl border"
                    />
                </div>
              </section>

              {/* When to Recalculate */}
              <section className="border-t pt-12">
                <Card className="not-prose border-l-4 border-l-orange-500">
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2 text-orange-800">
                      <AlertCircle className="w-5 h-5" /> When Should You Recalculate?
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="text-gray-700">
                    <p className="mb-4">Macros must adapt as your body adapts. Recalculate every 2–3 weeks or when:</p>
                    <ul className="list-disc pl-5 space-y-2 text-sm">
                      <li>Weight stalls for 14+ days</li>
                      <li>Energy or performance levels drop</li>
                      <li>Bodyweight changes by more than 5%</li>
                    </ul>
                  </CardContent>
                </Card>
              </section>

              {/* Who Should Use This */}
              <section>
                <h2 className="text-2xl font-bold mb-6">Free Macro Calculator – Who Should Use This?</h2>
                <div className="grid md:grid-cols-2 gap-4 not-prose">
                  {[
                    "Beginners confused by calories",
                    "People stuck despite dieting",
                    "Gym-goers wanting lean results",
                    "Vegetarians struggling with protein",
                    "Anyone tired of extreme plans"
                  ].map((item, i) => (
                    <div key={i} className="flex items-center gap-3 p-4 border rounded-xl bg-green-50 border-green-200">
                      <CheckCircle2 className="w-5 h-5 text-green-500 shrink-0" />
                      <span className="font-medium text-gray-700">{item}</span>
                    </div>
                  ))}
                </div>
              </section>

              {/* Conclusion */}
              <section className="text-center pb-12">
                <h2 className="text-3xl font-bold mb-4">Do Macro Calculators Work?</h2>
                <p className="text-muted-foreground max-w-2xl mx-auto mb-8">
                  Yes—when used correctly. A macro calculator is not a diet; it&apos;s a decision-making tool. 
                  Used properly, it teaches you portion control, food awareness, and sustainable fat loss.
                </p>
                <div className="bg-gray-900 text-white p-8 rounded-3xl">
                  <h3 className="text-white text-xl font-bold mb-2">Ready to start?</h3>
                  <p className="text-gray-400 text-sm mb-0">Use the calqulate.net tool above to get your custom blueprint.</p>
                </div>
              </section>

            </div>

            {/* Structured FAQ UI */}
            <div className="mt-12">
              <h2 className="text-2xl font-bold mb-8 text-center">Frequently Asked Questions</h2>
              <FAQSection faqs={faqs} />
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}