// components/plans/DietPlanPdfButton.tsx
"use client";

import { useState } from "react";
import type { DietPlan } from "@/lib/diet/diet-plans-data";

interface Props {
  plan: DietPlan;
  brandColor: string;
}

export default function DietPlanPdfButton({ plan, brandColor }: Props) {
  const [loading, setLoading] = useState(false);

  const handleDownload = async () => {
    setLoading(true);
    try {
      // Dynamic import keeps jsPDF out of the main bundle
      const { default: jsPDF } = await import("jspdf");
      const doc = new jsPDF({ unit: "pt", format: "a4" });

      const PAGE_W = doc.internal.pageSize.getWidth();
      const MARGIN = 40;
      let y = 60;

      // ── Header band ─────────────────────────────────
      doc.setFillColor(brandColor);
      doc.rect(0, 0, PAGE_W, 80, "F");
      doc.setTextColor("#ffffff");
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      doc.text("Calqulate.net", MARGIN, 35);
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.text("Personalized Diet Plan", MARGIN, 55);

      // ── Title ───────────────────────────────────────
      y = 110;
      doc.setTextColor("#0f172a");
      doc.setFontSize(22);
      doc.setFont("helvetica", "bold");
      doc.text(`${plan.shapeName} Body Shape — 7-Day Diet Plan`, MARGIN, y);
      y += 25;
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.setTextColor("#475569");
      doc.text(`Goal: ${plan.goal}`, MARGIN, y);
      y += 15;
      doc.text(`Daily Calories: ${plan.dailyCalories}`, MARGIN, y);
      y += 15;
      doc.text(
        `Macros — Protein ${plan.macros.protein}% | Carbs ${plan.macros.carbs}% | Fats ${plan.macros.fats}%`,
        MARGIN,
        y
      );
      y += 25;

      // ── Eat / Avoid columns ─────────────────────────
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.setTextColor("#16a34a");
      doc.text("✓ Foods to Eat", MARGIN, y);
      doc.setTextColor("#dc2626");
      doc.text("✗ Foods to Avoid", PAGE_W / 2, y);
      y += 15;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor("#0f172a");
      const maxRows = Math.max(plan.eat.length, plan.avoid.length);
      for (let i = 0; i < maxRows; i++) {
        if (plan.eat[i]) doc.text(`• ${plan.eat[i]}`, MARGIN, y);
        if (plan.avoid[i]) doc.text(`• ${plan.avoid[i]}`, PAGE_W / 2, y);
        y += 13;
      }
      y += 15;

      // ── 7-Day Plan ──────────────────────────────────
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.setTextColor("#0f172a");
      doc.text("7-Day Meal Plan", MARGIN, y);
      y += 18;

      doc.setFontSize(9);
      plan.weeklyPlan.forEach((day) => {
        if (y > 760) {
          doc.addPage();
          y = 60;
        }
        // Day header
        doc.setFillColor("#f1f5f9");
        doc.rect(MARGIN, y - 11, PAGE_W - MARGIN * 2, 16, "F");
        doc.setFont("helvetica", "bold");
        doc.setTextColor("#0f172a");
        doc.text(day.day, MARGIN + 6, y);
        y += 13;

        doc.setFont("helvetica", "normal");
        doc.setTextColor("#334155");
        const meals = [
          ["Breakfast", day.breakfast],
          ["Lunch", day.lunch],
          ["Snack", day.snack],
          ["Dinner", day.dinner],
        ];
        meals.forEach(([label, content]) => {
          doc.setFont("helvetica", "bold");
          doc.text(`${label}:`, MARGIN + 10, y);
          doc.setFont("helvetica", "normal");
          const lines = doc.splitTextToSize(content, PAGE_W - MARGIN * 2 - 80);
          doc.text(lines, MARGIN + 70, y);
          y += lines.length * 11 + 2;
        });
        y += 6;
      });

      // ── Fitness tip ────────────────────────────────
      if (y > 720) {
        doc.addPage();
        y = 60;
      }
      doc.setFillColor("#fef3c7");
      doc.rect(MARGIN, y, PAGE_W - MARGIN * 2, 50, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor("#92400e");
      doc.text("Fitness Tip", MARGIN + 10, y + 18);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      const tipLines = doc.splitTextToSize(plan.fitnessTip, PAGE_W - MARGIN * 2 - 20);
      doc.text(tipLines, MARGIN + 10, y + 32);

      // ── Footer ──────────────────────────────────────
      doc.setFontSize(8);
      doc.setTextColor("#94a3b8");
      doc.text(
        "Generated by Calqulate.net — Always consult a doctor or dietician before major dietary changes.",
        MARGIN,
        820
      );

      doc.save(`Calqulate-${plan.shapeName}-Diet-Plan.pdf`);
    } catch (err) {
      console.error("PDF generation failed:", err);
      alert("Could not generate PDF. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <button
      type="button"
      onClick={handleDownload}
      disabled={loading}
      className="inline-flex items-center gap-2 rounded-xl px-6 py-3 text-sm font-semibold text-white shadow-lg transition hover:shadow-xl disabled:opacity-60"
      style={{ backgroundColor: brandColor }}
    >
      {loading ? (
        <>
          <span className="h-4 w-4 animate-spin rounded-full border-2 border-white/40 border-t-white" />
          Generating...
        </>
      ) : (
        <>
          <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M4 16v2a2 2 0 002 2h12a2 2 0 002-2v-2M7 10l5 5m0 0l5-5m-5 5V4"
            />
          </svg>
          Download {plan.shapeName} Diet Plan PDF
        </>
      )}
    </button>
  );
}
