import { createAdminClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";

export default async function AdminProtocolsPage() {
  const admin = createAdminClient();
  const { data, error } = await admin
    .from("glp1_protocols")
    .select("user_id,medication,start_date,target_weight_kg,status,protocol_data,created_at")
    .order("created_at", { ascending: false })
    .limit(200);
  const { data: profiles } = await admin.from("profiles").select("id,email");
  const emailById = new Map<string, string>();
  for (const p of (profiles ?? []) as any[]) emailById.set(p.id, p.email);
  const rows = (data ?? []) as any[];

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">GLP-1 Autopilot protocols</h1>
        <p className="text-gray-500">Active titration protocols generated by members.</p>
      </div>

      {error && (
        <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">
          Could not read glp1_protocols — run migration <code>0003_longevity.sql</code> in Supabase.
        </div>
      )}

      <div className="overflow-x-auto rounded-2xl border border-gray-200 bg-white">
        <table className="w-full text-sm">
          <thead className="bg-gray-50 text-left text-gray-500">
            <tr>
              <th className="px-4 py-2.5 font-medium">Member</th>
              <th className="px-4 py-2.5 font-medium">Medication</th>
              <th className="px-4 py-2.5 font-medium">Dose path</th>
              <th className="px-4 py-2.5 font-medium">Weeks</th>
              <th className="px-4 py-2.5 font-medium">Status</th>
              <th className="px-4 py-2.5 font-medium">Created</th>
            </tr>
          </thead>
          <tbody>
            {rows.length === 0 && (
              <tr><td colSpan={6} className="px-4 py-6 text-center text-gray-400">No protocols yet.</td></tr>
            )}
            {rows.map((r, i) => {
              const p = r.protocol_data ?? {};
              return (
                <tr key={i} className="border-t border-gray-100">
                  <td className="px-4 py-2.5 text-gray-800">{emailById.get(r.user_id) ?? "—"}</td>
                  <td className="px-4 py-2.5">{p.medicationLabel ?? r.medication}</td>
                  <td className="px-4 py-2.5">{p.startDoseMg != null ? `${p.startDoseMg} → ${p.targetDoseMg} mg` : "—"}</td>
                  <td className="px-4 py-2.5">{p.totalWeeks ?? "—"}</td>
                  <td className="px-4 py-2.5">{r.status}</td>
                  <td className="px-4 py-2.5 text-gray-500">{r.created_at ? new Date(r.created_at).toLocaleDateString() : "—"}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}
